tts_prompt1 = (f"Good evening. This is Orson Welles. "
              f"And very happy I am to be back in the United States and back on the Columbia network "
              f"-- even for so short a visit as this one. Back with old friends like Johnny Dietz, "
              f"who's tonight's director, and Bernard Herrmann. "
              f"The Mercury Theatre presented tonight's radio play for the first time last year. "
              f"We came right out then and hailed it as a classic of the medium. "
              f"Nobody argued the point. A lot of people asked us to do it again so it's gratifying to get the chance now "
              f"- and to find a favorite of ours in this distinguished anthology of spook shows. "
              f"Personally, I've never met anybody who didn't like a good ghost story.")

tts_prompt2 = (f"... then, again I promise you, we haven't got it. "
               f"Not tonight. What we DO have is a thriller. "
               f"If it's half as good as we think it is, you can call"
               f" it a shocker. It's already been called 'a real Orson Welles story.'"
               f" Now, frankly, I don't know what this means. I've been on the air,"
               f" directing and acting in my own shows for quite a while now and I don't suppose "
               f"I've done more than half a dozen thrillers in all that time. "
               f"Honestly, I don't think even THAT many. But it seems I do have "
               f"a reputation for the uncanny. Quite possibly, a little escapade "
               f"of mine, involving a couple of planets which shall be nameless, "
               f"is responsible. Doesn't really matter. Don't think I disapprove "
               f"of thrillers. I don't. A story doesn't have to appeal"
               f" to the heart, it can also appeal to the spine. Sometimes"
               f" you want your heart to be warmed and - sometimes you want your"
               f" spine to tingle. The tingling, it's to be hoped, will be quite"
               f" audible as you listen tonight ... to 'The Hitch-Hiker.'"
               f" That's the name of our story, 'The Hitch-Hiker.'")